name: conventional-commits

on:
  pull_request:
    branches:
      - master

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: webiny/action-conventional-commits@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commitMessage: |
            - Your commit messages must follow the Conventional Commits specification!
            - More info: https://www.conventionalcommits.org/en/v1.0.0/
          failOnWarnings: "true"